{
  "type": "record",
  "name": "ShipmentLatest",
  "namespace": "invalid.quillmere.shipments",
  "fields": [
    {
      "name": "shipment_id",
      "type": "string"
    },
    {
      "name": "order_id",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string",
      "doc": "the latest status event per shipment"
    },
    {
      "name": "at",
      "type": "string"
    },
    {
      "name": "dock_id",
      "type": "string"
    },
    {
      "name": "trailer_id",
      "type": "string"
    }
  ]
}
